### ISSUE TITLE
Can't run on Windows - module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by DeemahSh** [taxjar/taxjar-python#25]
Hi
I've tried to run the API client on Windows 10 and looks like it's not supported. Could you please add Window implementation too?

File "C:\Programs\Python\Python36\lib\site-packages\taxjar\client.py", line 173, in _get_user_agent
    platform = ' '.join(os.uname())
AttributeError: module 'os' has no attribute 'uname'

Thank you

**Comment by fastdivision** [comment]
@DeemahSh This issue has been resolved in v1.9.1. Please let us know if you run into any additional problems on Windows. Thank you!
