### ISSUE TITLE
Cannot install on Python 3.10

### ISSUE THREAD

**Issue by vrslev** [taxjar/taxjar-python#32]
Since `jsonobject` [can't be compiled and installed on Python 3.10](https://github.com/dimagi/jsonobject/issues/184), this package can't be installed neither. [ERPNext](https://github.com/frappe/erpnext) depends on this library, so it can't be used on Python 3.10, too 😃
Do you consider using Pydantic instead of jsonobject for your data models?

**Comment by fsnlarson** [comment]
Our `taxjar` `pip3` install fails on `jsonobject` as well. Running python 3.7.10

**Comment by ankush** [comment]
@fastdivision @dubdromic the dependency was updated with a fix: https://github.com/dimagi/jsonobject/releases/tag/v1.0.0 


Maybe this can be added conditionally like this: `jsonobject>=1.0.0; python_version >= '3.10'`

**Comment by PeterJCLaw** [comment]
> Maybe this can be added conditionally like this: `jsonobject>=1.0.0; python_version >= '3.10'`

This shouldn't be needed -- the current version range already admits `jsonobject==1.0.0`, so `pip` (or whatever tool you're using to install pacakages) should work out that that's what's needed. Having just tested this in a fresh 3.10 virtualenv this does now work for me, so I propose that this issue be closed?

There's a separate question about whether this project should specify an _upper_ bound to their dependencies (e.g: `jsonobject >= 0.9.10, <2`) for safety, though that shouldn't impact this issue.

**Comment by vrslev** [comment]
Indeed, not it works!
