### ISSUE TITLE
Unexpected ValueError exception raised from inside the library when address is wrong

### ISSUE THREAD

**Issue by ram-nadella** [taxjar/taxjar-python#4]
```
  File "/srv/<clipped>tax.py", line 243, in tax
    tax_info = client.tax_for_order(payload)
  File "/home/vagrant/venv/nauman/lib/python2.7/site-packages/taxjar/client.py", line 28, in tax_for_order
    return self.responder(request)
  File "/home/vagrant/venv/nauman/lib/python2.7/site-packages/taxjar/response.py", line 7, in from_request
    return TaxJarResponse().data_from_request(request)
  File "/home/vagrant/venv/nauman/lib/python2.7/site-packages/taxjar/response.py", line 12, in data_from_request
    (type_name, values), = response.items()
ValueError: too many values to unpack
```

https://github.com/taxjar/taxjar-python/blob/master/taxjar/response.py#L12

There appears to be an unexpected exception being raised from with-in the library. While it was the client sending bad data (wrong state for city in the to address fields), having the library throw one of the expected [exceptions](https://github.com/taxjar/taxjar-python/blob/master/taxjar/exceptions.py) and providing the proper error message is what we would've expected.

**Comment by fastdivision** [comment]
@ram-nadella Are you using the latest version of our client v1.1.2, just pushed to PyPI today? I encountered the same problem earlier with a 400 response. Let me know, thanks!

**Comment by ram-nadella** [comment]
WHAT!? No we were using `taxjar==1.1.0` which I believe was the latest when we looked at it yesterday morning... Will try `1.1.2` to see if the issue goes away :)

Thanks for the quick reply @fastdivision

**Comment by ram-nadella** [comment]
@tbthorpe FYI
