### ISSUE TITLE
getting JSONDecodeError when Too Many Requests error

### ISSUE THREAD

**Issue by eb-maxiv** [taxjar/taxjar-python#9]
I'm getting an unexpected JSONDecodeError when making too many requests:

```  
  File "taxjar/client.py", line 34, in rates_for_location
    return self.responder(request)
  File "taxjar/response.py", line 7, in from_request
    return TaxJarResponse().data_from_request(request)
  File "taxjar/response.py", line 10, in data_from_request
    response = request.json()
  File "requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end) 
```

<img width="954" alt="screen shot 2018-07-16 at 14 46 08" src="https://user-images.githubusercontent.com/19844020/42774258-a4ad412e-8907-11e8-8ece-b3400047d8af.png">

**Comment by dubdromic** [comment]
@eb-maxiv Thanks for reporting; I'll have a look today and see what's going on.

**Comment by fastdivision** [comment]
@eb-maxiv This issue looks like it needs to be resolved directly in our API. We aren't returning valid JSON for a 429 error response. Our team is looking into this. Thanks for your patience!

**Comment by eb-maxiv** [comment]
Any news on this?

**Comment by fastdivision** [comment]
@eb-maxiv I'm still trying to prioritize this issue with our team to get a fix. Thanks for checking in!

**Comment by fastdivision** [comment]
Our API should now return a valid JSON error response for 429 errors with `error` and `detail` attributes included. Thank you!
